version: '2'
services:
  web:
    build: 'Website Docker'
    ports:
      - "5000:5000"
  mysql:
    build: 'Mysql Docker'
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: Aoc
      MYSQL_ROOT_PASSWORD: bluecrew
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: root
      MYSQL_PASSWORD: bluecrew
